const data = [
    {
        'id' : 1,
        'img' : 'https://static.naewna.com/uploads/news/source/334197.jpg',
        'title_th' : 'ข่าวนายก',
        'title_en' : 'Prime Minister NEWS',
        'description_th' : 'วันที่ 10 มี.ค. 65 นายธนกร วังบุญคงชนะ โฆษกประจำสำนักนายกรัฐมนตรี เปิดเผยว่า พล.อ.ประยุทธ์ จันทร์โอชา นายกรัฐมนตรีและรมว.กลาโหม รับทราบรายงานเกิดเหตุคนร้าย ลอบวางระเบิด ขณะเจ้าหน้าที่ ออกลาดตระเวนด้วยรถยนต์ บนถนนสาย 410 ยะลา-เบตง ถึงบริเวณ บ.เงาะกาโป หมู่ 3 ต.บันนังสตา อ.บันนังสตา จ.ยะลา ทำให้เจ้าหน้าที่ ทพ.ฉก. 30 และประชาชนบริเวณใกล้เคียงได้รับบาดเจ็บ โดยนายกฯ สั่งการด่วน ให้เจ้าหน้าที่ฝ่ายความมั่นคงเร่งติดตามผู้ก่อเหตุ และเพิ่มกำลังเฝ้าระวังตลอดเส้นทางคมนาคม รวมถึงเส้นทางรางและถนนในพื้นที่เกิดเหตุ พร้อมให้รายงานความคืบหน้าให้ทราบอย่างต่อเนื่องด้วยนายธนกร กล่าวว่า สำหรับผู้ที่ได้รับบาดเจ็บ นายกฯ ได้มอบหมายให้ผู้ว่าราชการจังหวัดยะลาหรือหัวหน้าส่วนราชการเป็นผู้แทนนายกฯ เดินทางไปเยี่ยมผู้ได้รับบาดเจ็บที่โรงพยาบาล รวมถึงตรวจเยี่ยมประชาชนบริเวณที่เกิดเหตุ เพื่อเป็นขวัญกำลังใจและเร่งให้ความช่วยเหลืออย่างเต็มที่ พร้อมกำชับฝ่ายความมั่นคงในพื้นที่ ปรับแผนและวางมาตรการรักษาความปลอดภัยทุกพื้นที่อย่างเข้มข้นโดยเฉพาะในพื้นที่เปราะบางทุกจุดด้วย.',
        'description_en' : "On March 10, 65, Thanakorn Wangboonkongchana, spokesman for the Prime Minister's Office, revealed that Gen. Prayut Chan-o-cha, Prime Minister and Minister of Defense Acknowledge the report of an assassination attack while the officers Patrol with a car on Route 410 Yala-Betong to the area of ​​Ban Ngao Kapo, Village No. 3, Bannang Sata Subdistrict, Bannang Sata District, Yala Province, causing injuries to DDPS officers and nearby people, ordered by the Prime Minister. Urgent. Let security officials speed up the tracking of the perpetrators. and increase surveillance throughout the transportation route including rail and road routes in the accident area Ready to report the progress continuously. Mr. Thanakorn said that for those injured, the Prime Minister has assigned the governor of Yala Province or the head of a government agency to be the prime minister's representative. Travel to visit the injured at the hospital including visiting people at the scene of the accident In order to encourage and accelerate the full assistance Ready to charge the security department in the area Plan and implement intensive security measures in all areas, especially in all vulnerable areas." 
    },
    {
        'id' : 2,
        'img' : 'https://img.pptvhd36.com/health/thumbor/2022/03/10/cusArticle-2f4ce9bafa.jpg',
        'title_th' : 'ควิดวันนี้ ยอดRT-PCR รวม ATK พุ่งทะลุ 7.2 หมื่นราย เช็ก 10 จังหวัดติดเชื้อสูงสุด',
        'title_en' : 'Quit today, total RT-PCR total ATK surpassed 7.2 thousand, Czech 10 provinces are the most infected.',
        'description_th' : 'ศูนย์บริหารสถานการณ์โควิด – 19 (ศบค.) รายงานสถานการณ์โควิด-19 ประจำวันที่ 10 มี.ค. 2565 โดยมีผู้ติดเชื้อรายใหม่รวม 22,984 ราย จำแนกเป็น ผู้ป่วยจากในประเทศ 22,937 รายผู้ป่วยมาจากต่างประเทศ 47 ราย ผู้ป่วยสะสม 888,422 ราย (ตั้งแต่ 1 ม.ค. 2565) หายป่วยกลับบ้าน 24,161 ราย หายป่วยสะสม 699,517 ราย (ตั้งแต่ 1 ม.ค. 2565) ผู้ป่วยกำลังรักษา 220,334 ราย เสียชีวิต 74 ราย',
        'description_en' : "The Center for Covid-19 Situation Administration (BDC) reports the situation of COVID-19 as of March 10, 2022, with a total of 22,984 new cases, categorized as 22,937 domestic cases. 47 cases from abroad, 888,422 cumulative cases (since Jan 1, 2022), 24,161 recoveries, 699,517 cumulative recoveries (since Jan 1, 2022), 220,334 cases, 74 deaths." 
    },
    {
        'id' : 3,
        'img' : 'https://static.thairath.co.th/media/HCtHFA7ele6Q2dUMyaN7gtTpGIgLGPTMFihuQczd7x1QGvc9U1fRmhrsY9456v4Jch.webp',
        'title_th' : 'นาทีระทึก ยูเครนซุ่มโจมตีรถถังรัสเซีย สกัดเริ่มกลับมาลุยบุกกรุงเคียฟ',
        'title_en' : 'Thrilling moment Ukraine ambushed Russian tanks The extraction began to come back to invade Kiev.',
        'description_th' : 'เมื่อ 10 มี.ค. 65 เดลี่เมลรายงาน ประธานาธิบดีวลาดิเมียร์ ปูติน ของรัสเซียกลับมาเริ่มเดินหน้าเคลื่อนขบวนรถถังมุ่งหน้าสู่กรุงเคียฟ เมืองหลวงยูเครน ขณะนี้อยู่ห่างจากบริเวณชานกรุงเคียฟเพียงไม่กี่ไมล์เท่านั้น โดยกองกำลังรัสเซียได้ปฏิบัติการโจมตีกรุงเคียฟ เมื่อวันพุธที่ 9 มีนาคม ตามเวลาท้องถิ่นมาจากสองทิศทาง ทั้งจากทางทิศตะวันตกและตะวันออก การโจมตีกรุงเคียฟจากทางฝั่งทิศตะวันตก รัสเซียได้โอบล้อมเมืองเอียร์ปินไว้ได้ ส่วนทางทิศตะวันออก ขบวนรถถังรัสเซียได้เคลื่อนผ่านเมืองโบรวารี ขณะที่มีคลิปเผยแพร่บนโลกออนไลน์ แสดงให้เห็นนาทีรถถังของรัสเซียคันหนึ่งได้ถูกทหารยูเครนดักซุ่มโจมตี เพื่อต้องการขัดขวาง และทำให้ขบวนรถถังรัสเซียต้องถอยกลับไป จากการดักฟังสัญญาณสื่อสารทางวิทยุ ทราบว่าขบวนรถถังของรัสเซียได้รับความเสียหายอย่างหนัก หลังถูกยูเครนซุ่มโจมตี และทำให้ผู้บัญชาการรบในภูมิภาคนี้ของรัสเซียถูกสังหาร อย่างไรก็ตาม ยังไม่มีการตรวจสอบยืนยันข้อเท็จจริงในเรื่องนี้ ด้านที่ปรึกษากระทรวงมหาดไทยของยูเครน วาดิม ดีนีเซนโก กล่าวว่า กำลังทหารยูเครนได้โจมตีขบวนรถถังรัสเซียเพื่อให้ล่าถอยกลับไปเมื่อเช้าวันนี้ ตามเวลาท้องถิ่น และขณะนี้การสู้รบ ยังคงดำเนินต่อไป โดยเมื่อคืนที่ผ่านมาถือเป็นคืนที่ยากลำบากทีเดียว แต่โดยทั่วไปแล้ว พวกเราสามารถพูดได้ว่ากองทัพยูเครนได้ตอบโต้ขบวนรถถังรัสเซียใกล้กรุงเคียฟ แต่ขณะนี้ยังไม่มีข้อมูลรายละเอียดขณะที่นักวิเคราะห์ด้านสงครามหลายคน กังวลว่าการที่รัสเซียส่งเครื่องบินรบบินทิ้งระเบิดโจมตีโรงพยาบาลแม่และเด็กในเมืองมาริอูโปล ทำให้มีผู้เสียชีวิต 3 ศพ รวมทั้งเด็กหญิงวัย 6 ขวบ และการโจมตีเมืองคาร์คีฟ เมืองใหญ่อันดับสองของยูเครนอย่างหนักนั้น เราอาจได้เห็นการโจมตีรุนแรงแบบนี้ในเมืองหลวงของยูเครน',
        'description_en' : "On March 10, 65, the Daily Mail reported. Russian President Vladimir Putin has resumed his march of tanks towards Kiev. Ukrainian capital It is now only a few miles from the suburbs of Kiev. The Russian forces attacked the city of Kiev. On Wednesday, March 9, local time came from two directions. both from the west and the east attacking Kiev from the west coast The Russians had encircled the city of Erpin. eastern part A convoy of Russian tanks passed through the city of Brovary. while the clip is published online It shows the moment a Russian tank is ambushed by Ukrainian soldiers. to interrupt and caused the Russian tank convoys to retreat. from eavesdropping on radio communications Knowing that the Russian convoy was badly damaged. after being ambushed by Ukraine This resulted in the killing of Russian commanders in this region. Ukraine's interior ministry adviser Vadim Dinisenko said Ukrainian troops had attacked a convoy of Russian tanks to retreat earlier this morning. according to local time And now the battle continues Last night was a very difficult night. but in general We can say that the Ukrainian army responded to a convoy of Russian tanks near Kiev. But there is currently no detailed information. While many war analysts Concerned about Russian fighter jets attacking a maternity and child hospital in Mariupol Three people were killed, including a 6-year-old girl, and an attack on Kharkiv. Ukraine's second largest city is heavily We may have seen such violent attacks in the Ukrainian capital." 
    },
]

export default { data }